$(document).ready(function(){
    $(window).scroll(function(){
        if(this.scrollY>150){
            $('.navbar').addClass("sticky");
        }else{
            $('.navbar').removeClass("sticky");
        }
    })
})